# Generated by Django 3.2.9 on 2024-04-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('education', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('communication', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('household', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('healthcare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
            ],
        ),
    ]
